routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::get('/product/{id}', 'HomeController@product_detail');

Route::group(["prefix" => "dashboard"], function(){
    Route::get('/', 'DashboardController@index');    

    // users controller
    Route::resource('users', 'UsersController');
    Route::get('/users/delete/{id}', 'UsersController@destroy');

    // user_types controller
    Route::resource('/user_types', 'UserTypesController');
    Route::get('/user_types/delete/{id}', 'UserTypesController@destroy');

    // products controller
    Route::resource('/products', 'ProductsController');
    Route::get('/products/delete/{id}', 'ProductsController@destroy');
    Route::get('/products/change_status/{id}', 'ProductsController@change_status');
    Route::get('/products/create_image/{id}', 'ProductsController@create_image'); 
    Route::post('/products/store_image', 'ProductsController@store_image'); 
    Route::get('/products/delete_product_image/{id}', 'ProductsController@delete_product_image');     

    // product_types controller
    Route::resource('/product_types', 'ProductTypesController');
    Route::get('/product_types/delete/{id}', 'ProductTypesController@destroy');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    public function product_type()
    {
        return $this->belongsTo('App\Models\ProductType', 'product_type_id');
    }

    public function product_images()
    {
        return $this->hasMany('App\Models\ProductImage');
    }
}

app/Models/ProductType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    use HasFactory;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;
use Hash;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {                
        return view('admins/dashboard');
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use File;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\Product;
use App\Models\ProductType;
use App\Models\ProductImage;

class ProductsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();        
        return view("dashboard.products.index",compact(["products"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product_types = ProductType::all();
        return view("dashboard.products.create",compact(["product_types"]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        // dd($input);
        $random = Str::random(5);
        
        $product = new Product;                
        $product->name = $input['name'];
        $product->price = $input['price'];
        $product->product_type_id = $input['product_type_id'];
        $product->description = $input['description'];
        $product->quantity = $input['quantity'];
        $product->link_tokped = $input['link_tokped'];
        $product->link_shope = $input['link_shope'];
        $product->link_lazada = $input['link_lazada'];
        $product->link_bukalapak = $input['link_bukalapak'];
        $product->status = 1;
        
        if(isset($input['image'])){
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/products/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/products/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $product->image = $destinationPath.'/'.$filename;
            }
        }
        $product->save();

        
        $i = 0;
        $count_looping = $input['count_looping_product_image'];
        for ($x = 0; $x < $count_looping; $x++) {                
            $product_image = new ProductImage;
            $product_image->product_id = $product->id;

            // upload image
            if(isset($input['document'][$i])){
                $files = $input['document'][$i];
                if ($files) {
                    $destinationPath    = 'uploads/attachment/product_images/'; // The destination were you store the document.
                    if(!(file_exists(public_path('/uploads/attachment/product_images/'))))
                    {
                        File::makeDirectory($destinationPath, $mode = 0777, true, true);
                    }
                    $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                    $mime_type          = $files->getMimeType(); // Gets this example image/png
                    $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                    $filename           = time().'-'.$filename; // random file name to replace original
                    $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                    $product_image->image = $destinationPath.'/'.$filename;
                }
            }
            $product_image->save();
            $i++;
        }
                
        \Session::flash('success','Data Produk berhasil dibuat');
        return redirect("dashboard/products/");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view("dashboard.products.show",compact(["product"]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $product_types = ProductType::all();
        return view("dashboard.products.edit",compact(["product", "product_types"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $product = Product::find($id);
        $product->name = $input["name"];
        $product->price = $input['price'];
        $product->product_type_id = $input['product_type_id'];
        $product->description = $input['description'];
        $product->quantity = $input['quantity'];
        $product->link_tokped = $input['link_tokped'];
        $product->link_shope = $input['link_shope'];
        $product->link_lazada = $input['link_lazada'];
        $product->link_bukalapak = $input['link_bukalapak'];

        if ($request->file('image')) {
            if(!is_null($product->image)){
                unlink($product->image);                
            }
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/products/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/products/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $product->image = $destinationPath.'/'.$filename;
            }            
        }
        $product->save();
        \Session::flash('success','Product berhasil di update');
        return redirect("/dashboard/products/");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        if(!is_null($product->image)){
            unlink($product->image);                
        }
        
        if(!is_null($product->product_images)){                            
            foreach($product->product_images as $product_image){
                if(!is_null($product_image->image)){
                    // remove image
                    unlink($product_image->image);
                }
                $product_image->delete();
            }
        }
        
        $product->delete();
        \Session::flash('success','Product berhasil di dalete');

        return redirect("/dashboard/products");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function change_status($id)
    {
        $product = Product::find($id);
        // dd($product);
        if($product->status == 1){
            $product->status = 0;
        }else{
            $product->status = 1;
        }
        $product->save();
        \Session::flash('success','Status Produk berhasil di rubah');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function create_image($id)
    {
        $product = Product::find($id);        
        $product->save();

        return view("dashboard.products.create_image",compact(["product"]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store_image(Request $request)
    {
        $input = $request->all();
        $random = Str::random(5);
        
        $i = 0;
        $count_looping = $input['count_looping_product_image'];
        for ($x = 0; $x < $count_looping; $x++) {                
            $product_image = new ProductImage;
            $product_image->product_id = $input['product_id'];

            // upload image
            if(isset($input['document'][$i])){
                $files = $input['document'][$i];
                if ($files) {
                    $destinationPath    = 'uploads/attachment/product_images/'; // The destination were you store the document.

resources/views/dashboard/products/create_image.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Form Data Gambar Produk</h3>
    </div>
    <br />
    <form class="form-horizontal" role="form" method="POST" action="{{ url('/dashboard/products/store_image') }}" enctype="multipart/form-data">
        <input type="hidden" class="form-control" name="created_by" id="created_by" value="{{ Auth::user()->id }}">
        <input type="hidden" class="form-control" name="product_id" id="product_id" value="{{ $product->id }}">
        @csrf 
        <div class="panel-body">        
            <br>
            <h6>Foto Produk<h6>
            <div class="form-group row">
                <div id="dinamic_form">
                    <div id="row_0">              
                        <div class="box-body">
                            <div class="row">                
                            <div class="col-xs-3">
                                <a id="add" class="btn btn-success btn-sm"> <i class="fa fa-plus"></i></a>
                                <a id="remove" class="btn btn-danger btn-sm"><i class="fa fa-remove"></i></a>
                            </div>                        
                            <div class="col-xs-3">
                                <input type="file" class="form-control" id="document_0" name="document[0]" data-max-size="2097152" placeholder="Upload File " required="">                                            
                            </div>                                                                                                
                            <div class="col-xs-3">
                                <p class="text-red">* Ukuran Maksimal File 2MB</p>
                                <p class="text-red">* Format File : pdf, dokumen, rar, zip</p>
                                <p class="text-red">* Hapus field jika tidak di gunakan</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" class="form-control" name="count_looping_product_image" id="count_looping_product_image" value="1">

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Create') }}
                    </button>
                    <a class="btn btn-success" href="/dashboard/users/">Back</a>
                </div>
            </div>
        </div>
    </form>
    <!-- End Horizontal Form -->      
</section>
<!-- End -->
<script>
    $(function(){
        $('.select2').select2();

        $('.summernote').summernote({
            height: 350
        });

        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'YYYY-MM-DD'
        });

        var i = 1;
        $('#add').click(function(){  
            $('#dinamic_form').append('<div id="row_'+i+'"><div class="box-body"><div class="row"><div class="col-xs-3"></div><div class="col-xs-3"><input type="file" class="form-control" id="document['+i+']" name="document['+i+']" placeholder="Upload File " required=""></div><div class="col-xs-2"></div></div></div></br>');
            ++i;
            $('#count_looping_product_image').val(i);
        });

        $('#remove').click(function(){
            if(i != 0){
                --i;
            }
            $('#count_looping_product_image').val(i);
            $('#row_'+i).remove();               
        });

        var image = $('#image');        
        var maxSize = image.data('max-size');
        var document = $('#document_0');
        $("form").submit(function(){
            if(image.val() != '' && image.get(0).files[0].size>maxSize){
                alert('file gambar sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }else if(document.val() != '' && document.get(0).files[0].size>maxSize){
                alert('file dokumen repot melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection

resources/views/dashboard/products/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Form Data Post</h3>
    </div>
    <br />
    <form class="form-horizontal" role="form" method="POST" action="{{ route('products.update', $product->id) }}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="panel-body">
        <div class="row">        
            <div class="col-lg-12">
                <div class="margin-bottom-50">                    
                    <br />
                    <!-- Horizontal Form -->                                           
                    <input type="hidden" class="form-control" name="updated_by" id="updated_by" value="{{ Auth::user()->id }}">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Nama</label>
                        </div>
                        <div class="col-md-10">
                            <input id="name" type="text" class="form-control" name="name"  placeholder="Input nama user" value="{{$product->name}}" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Produk Tipe</label>
                        </div>
                        <div class="col-md-10">
                            <select id="product_type_id" type="text" class="form-control select2" name="product_type_id">
                                <option value="">--- Pilih Produk Tipe ---</option>
                                @foreach ($product_types as $product_type)
                                    @if($product_type->id == $product->product_type_id )
                                    <option value="{{ $product_type->id }}" selected >{{$product_type->name }}</option>
                                    @else
                                    <option value="{{ $product_type->id }}">{{$product_type->name }}</option>
                                    @endif
                                @endforeach
                            </select>

                            @if ($errors->has('product_type_id'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('product_type_id') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    @if($product->image)
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Gambar Post</label>
                        </div>
                        <div class="col-md-4">
                            <img id="image" src="/{{$product->image}}" alt="{{$product->image}}" style="width:100%;max-width:300px">                                
                        </div>
                        <div class="col-md-6">
                            <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar Sidang" autofocus>

                            @if ($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>                            
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-2"></div>
                        <div class="col-xs-10">
                            <p class="text-red">* Upload jika ingin merubah gambar post</p>
                            <p class="text-red">* Ukuran Maksimal File 2MB</p>
                            <p class="text-red">* Format File : jpeg, jpg, png</p>
                        </div>
                    </div>                        
                    @else
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label class="form-control-label" for="l0">Gambar Post</label>
                        </div>
                        <div class="col-md-8">
                            <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar Sidang" autofocus>

                            @if ($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>                            
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4"></div>
                        <div class="col-xs-2">
                            <p class="text-red">* Ukuran Maksimal File 2MB</p>
                            <p class="text-red">* Format File : jpeg, jpg, png</p>
                        </div>
                    </div>
                    @endif
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Harga</label>
                        </div>
                        <div class="col-md-10">
                            <input id="price" type="text" class="form-control" name="price" value="{{$product->price}}"  placeholder="Input harga produk" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Deskripsi</label>
                        </div>
                        <div class="col-md-10">
                            <textarea id="description" name="description" class="form-control summernote" rows="4" cols="50" autofocus>
                            {{$product->description}}
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Jumlah</label>
                        </div>
                        <div class="col-md-10">
                            <input id="quantity" type="text" class="form-control" name="quantity" value="{{$product->quantity}}"  placeholder="Input Jumlah produk" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">link Tokped</label>
                        </div>
                        <div class="col-md-10">
                            <input id="link" type="text" class="form-control" name="link_tokped" value="{{$product->link_tokped}}" placeholder="Input Link tokped produk" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">link Shope</label>
                        </div>
                        <div class="col-md-10">
                            <input id="link" type="text" class="form-control" name="link_shope" value="{{$product->link_shope}}" placeholder="Input Link tokped produk" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">link Lazada</label>
                        </div>
                        <div class="col-md-10">
                            <input id="link" type="text" class="form-control" name="link_lazada" value="{{$product->link_lazada}}" placeholder="Input Link tokped produk" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">link Bukalapak</label>
                        </div>
                        <div class="col-md-10">
                            <input id="link" type="text" class="form-control" name="link_bukalapak" value="{{$product->link_bukalapak}}" placeholder="Input Link tokped produk" autofocus>
                        </div>
                    </div>
                </div>
            </div>
        </div>  

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Update') }}
                </button>
                <a class="btn btn-success" href="/dashboard/products/">Back</a>
            </div>
        </div>
    </div>
    </form>
    <!-- End Horizontal Form -->      
</section>

<!-- End -->
<script>
    $(function(){
        $('.select2').select2();

        $('.summernote').summernote({
            height: 350
        });

        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'YYYY-MM-DD'
        });

        var image = $('#image');        
        var maxSize = image.data('max-size');
        var document = $('#document_0');
        $("form").submit(function(){
            if(image.val() != '' && image.get(0).files[0].size>maxSize){
                alert('file gambar sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }else if(document.val() != '' && document.get(0).files[0].size>maxSize){
                alert('file dokumen repot melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection